"""empty message

Revision ID: 00a24a23a673
Revises: 3aadc887f2c9
Create Date: 2024-02-05 21:30:58.050257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a24a23a673'
down_revision = '3aadc887f2c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.alter_column('episode_id',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('opening_crawl',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('director',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('producer',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('release_date',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('created',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('edited',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('diameter',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('rotation_period',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('orbital_period',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('gravity',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('surface_water',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('created',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('edited',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.alter_column('classification',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('designation',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('average_heigth',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('average_lifespan',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('eye_colors',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('hair_colors',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('skin_colors',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('homeworld',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('created',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('edited',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('starship_class',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('manufacturer',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('length',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('cost_in_credits',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('crew',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('passengers',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('max_atmosphering_speed',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('hiper_drive_rating',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('MGLT',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('cargo_capacity',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('consumables',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('created',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('edited',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('vehicle_class',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('manufacturer',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('length',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('cost_in_credits',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('crew',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('passengers',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('max_atmosphering_speed',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('cargo_capacity',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('consumables',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('created',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('edited',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('edited',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('created',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('consumables',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('cargo_capacity',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('max_atmosphering_speed',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('passengers',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('crew',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('cost_in_credits',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('length',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('manufacturer',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('vehicle_class',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('edited',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('created',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('consumables',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('cargo_capacity',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('MGLT',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('hiper_drive_rating',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('max_atmosphering_speed',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('passengers',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('crew',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('cost_in_credits',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('length',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('manufacturer',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('starship_class',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('edited',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('created',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('homeworld',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('skin_colors',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('hair_colors',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('eye_colors',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('average_lifespan',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('average_heigth',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('designation',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('classification',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('edited',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('created',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('surface_water',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('gravity',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('orbital_period',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('rotation_period',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('diameter',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('edited',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('created',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('release_date',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('producer',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('director',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('opening_crawl',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('episode_id',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###
