"""empty message

Revision ID: 2367f32dd383
Revises: 8c879679bef1
Create Date: 2024-01-31 20:33:27.294482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2367f32dd383'
down_revision = '8c879679bef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_people', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'people', ['id_people'], ['id'])

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_people', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'people', ['id_people'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_people')

    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_people')

    # ### end Alembic commands ###
