"""empty message

Revision ID: 3aadc887f2c9
Revises: 93bbe8b16e6f
Create Date: 2024-02-05 21:28:02.469012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aadc887f2c9'
down_revision = '93bbe8b16e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('birth_year',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('skin_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('homeworld',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('mass',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('created',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('edited',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('edited',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('created',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('mass',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('homeworld',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('skin_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('birth_year',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###
