"""empty message

Revision ID: 45f1b26f8a79
Revises: d23a07f3fdfd
Create Date: 2024-01-31 20:03:59.549899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f1b26f8a79'
down_revision = 'd23a07f3fdfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_people', sa.Integer(), nullable=True),
    sa.Column('id_vehicles', sa.Integer(), nullable=True),
    sa.Column('id_species', sa.Integer(), nullable=True),
    sa.Column('id_films', sa.Integer(), nullable=True),
    sa.Column('id_starships', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_films'], ['films.id'], ),
    sa.ForeignKeyConstraint(['id_people'], ['people.id'], ),
    sa.ForeignKeyConstraint(['id_species'], ['species.id'], ),
    sa.ForeignKeyConstraint(['id_starships'], ['starships.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_vehicles'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
