"""empty message

Revision ID: 7ed6d477537c
Revises: 575cd79047dc
Create Date: 2024-02-05 18:22:11.501787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed6d477537c'
down_revision = '575cd79047dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_planets', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorites_id_species_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planets', ['id_planets'], ['id'])
        batch_op.drop_column('id_species')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_id_starships_fkey', type_='foreignkey')
        batch_op.drop_column('id_starships')

    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.drop_constraint('species_id_people_fkey', type_='foreignkey')
        batch_op.drop_column('id_people')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_people', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('species_id_people_fkey', 'people', ['id_people'], ['id'])

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_starships', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('people_id_starships_fkey', 'starships', ['id_starships'], ['id'])

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_species', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_id_species_fkey', 'species', ['id_species'], ['id'])
        batch_op.drop_column('id_planets')

    # ### end Alembic commands ###
