"""empty message

Revision ID: 8c879679bef1
Revises: 45f1b26f8a79
Create Date: 2024-01-31 20:17:37.946088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c879679bef1'
down_revision = '45f1b26f8a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_starships', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'starships', ['id_starships'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_starships')

    # ### end Alembic commands ###
