"""empty message

Revision ID: 93bbe8b16e6f
Revises: a066d0966893
Create Date: 2024-02-05 21:24:22.664780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93bbe8b16e6f'
down_revision = 'a066d0966893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_species', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'species', ['id_species'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_species')

    # ### end Alembic commands ###
