"""empty message

Revision ID: a066d0966893
Revises: 7ed6d477537c
Create Date: 2024-02-05 21:21:01.565642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a066d0966893'
down_revision = '7ed6d477537c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_people', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'people', ['id_people'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_people')

    # ### end Alembic commands ###
