"""empty message

Revision ID: edeb820d3e64
Revises: 00a24a23a673
Create Date: 2024-02-05 22:12:55.105660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edeb820d3e64'
down_revision = '00a24a23a673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_id_films_fkey', type_='foreignkey')
        batch_op.drop_column('id_films')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_films', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('favorites_id_films_fkey', 'films', ['id_films'], ['id'])

    # ### end Alembic commands ###
